Repository woorifisa-service-dev-4th/frontend-whoareyou, pull requests merged in 2025-01, with the labels that each got.

#8 chore: update DummyData
  src/model/image.js
  src/model/initData.jsx
  src/model/status.js
Labels: chore

#10 Feat/4
  package.json
  postcss.config.js
  src/components/CommentSection.jsx
  src/components/ToastEditor.jsx
  src/contexts/QnAContexts.jsx
  src/index.css
  src/model/comment.js
  src/model/image.js
  src/model/initData.jsx
  src/model/post.js
  src/model/status.js
Labels: feature

#11 feat : 게시글 상세 조회 페이지 구조화
  src/components/postdetails/ForumPost.jsx
  src/components/postdetails/PostDeails.jsx
  src/components/ui/CommentSection.jsx
  src/components/ui/Header.jsx
Labels: feature

#22 Feat/6 게시물 등록 기능 추가
  src/components/posts/CategoryFilter.jsx
  src/components/posts/ClassFilter.jsx
  src/components/posts/CourseFilter.jsx
  src/components/posts/PostEditor.jsx
  src/contexts/QnAContexts.jsx
  src/layouts/Header.jsx
Labels: feature

#31 Feat/30 root페이지랑 현재까지 작업한(post 상세페이지 및 댓글)거 합치기
  src/component/QuestionCard.jsx
  src/component/QuestionContent.jsx
  src/component/Questionboard.jsx
  src/component/SortingTable.jsx
  src/component/button/CategoryButton.jsx
  src/component/button/CustomButton.jsx
  src/component/button/SectionButton.jsx
  src/components/QuestionCard.jsx
  src/components/QuestionContent.jsx
  src/components/SortingTable.jsx
  src/components/button/CategoryButton.jsx
  src/components/button/SectionButton.jsx
  src/components/comments/Comment.jsx
  src/components/posts/CategoryFilter.jsx
  src/components/posts/ClassFilter.jsx
  src/components/posts/PostDetails.jsx
  src/components/posts/PostEditor.jsx
  src/contexts/QnAContexts.jsx
  src/model/initData.jsx
Labels: feature, refactor
